name: Pull request merged workflow

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Github Actions Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.*
        include-prerelease: true
    - name: Build Reason
      run: echo ${{github.ref}} and ${{github.event_name}}
    - name: Build with dotnet
      run: find . -path ./template -prune -false -o -name '*.csproj' -execdir dotnet build --configuration Release --nologo {} \;
    # - name: Run tests
      # run: dotnet test --configuration Release --no-build --nologo
    - name: Push prerelease package to NuGet
      run: ./push.sh carter nuget
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
