# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Update Carter NuGet package references

on:
  push:
    branches:
      - mderriey/reusable-workflows
  workflow_dispatch:
    inputs:
      includePrerelease:
        type: boolean
        default: false
        description: Whether to include prerelease versions when searching for the latest version of the Carter NuGet package

      commitAndPush:
        type: boolean
        default: false
        description: Whether to commit and push the changes; Useful to test the process by looking at the resulting Git diff

jobs:
  update-carter-package-references:
    uses: CarterCommunity/.github/.github/workflows/workflow.yml@mderriey/reusable-workflows
    with:
      includePrerelease: false
      commitAndPush: false
